USE `adamia_dev`;
SET NAMES utf8mb4;

CREATE TABLE cau_articulos (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_empresa INT NOT NULL,
  tipo ENUM('activo','uniforme') NOT NULL,
  nombre VARCHAR(180) NOT NULL,
  codigo VARCHAR(80) NOT NULL,
  categoria VARCHAR(100) NOT NULL,
  marca VARCHAR(100) NULL,
  modelo VARCHAR(150) NULL,
  numero_serie VARCHAR(120) NULL COMMENT 'Normalizar cadena vacia a NULL',
  talla VARCHAR(30) NULL,
  color VARCHAR(60) NULL,
  retornable BOOLEAN NOT NULL DEFAULT TRUE,
  stock_minimo INT UNSIGNED NOT NULL DEFAULT 0,
  costo_referencia DECIMAL(12,2) NOT NULL DEFAULT 0,
  meses_reposicion SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by INT NOT NULL,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  updated_by INT NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cau_articulos_empresa_id (id_empresa, id),
  CONSTRAINT ck_cau_articulos_version CHECK (version > 0),
  UNIQUE KEY uq_cau_art_codigo (id_empresa, codigo),
  UNIQUE KEY uq_cau_art_serie (id_empresa, numero_serie),
  KEY ix_cau_art_busqueda (id_empresa, tipo, activo, nombre),
  CONSTRAINT ck_cau_art_costo CHECK (costo_referencia >= 0),
  CONSTRAINT ck_cau_art_bool CHECK (retornable IN (0,1) AND activo IN (0,1)),
  CONSTRAINT ck_cau_art_codigo CHECK (CHAR_LENGTH(TRIM(codigo)) > 0),
  CONSTRAINT ck_cau_art_serie CHECK (numero_serie IS NULL OR CHAR_LENGTH(TRIM(numero_serie)) > 0),
  CONSTRAINT fk_cau_articulos_empresa FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cau_ubicaciones (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_empresa INT NOT NULL,
  nombre VARCHAR(150) NOT NULL,
  id_sucursal INT NULL,
  descripcion TEXT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by INT NOT NULL,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  updated_by INT NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cau_ubicaciones_empresa_id (id_empresa, id),
  CONSTRAINT ck_cau_ubicaciones_version CHECK (version > 0),
  UNIQUE KEY uq_cau_ubi_nombre (id_empresa, nombre),
  KEY ix_cau_ubi_sucursal (id_empresa, id_sucursal),
  CONSTRAINT ck_cau_ubi_activo CHECK (activo IN (0,1)),
  CONSTRAINT fk_cau_ubicaciones_empresa FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cau_existencias (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_empresa INT NOT NULL,
  id_articulo BIGINT UNSIGNED NOT NULL,
  id_ubicacion BIGINT UNSIGNED NOT NULL,
  cantidad_disponible INT UNSIGNED NOT NULL DEFAULT 0,
  cantidad_revision INT UNSIGNED NOT NULL DEFAULT 0,
  cantidad_baja INT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by INT NOT NULL,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  updated_by INT NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cau_existencias_empresa_id (id_empresa, id),
  CONSTRAINT ck_cau_existencias_version CHECK (version > 0),
  UNIQUE KEY uq_cau_exi_art_ubi (id_empresa, id_articulo, id_ubicacion),
  KEY ix_cau_exi_ubicacion (id_empresa, id_ubicacion),
  CONSTRAINT fk_existencias_articulo FOREIGN KEY (id_empresa, id_articulo) REFERENCES cau_articulos (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_existencias_ubicacion FOREIGN KEY (id_empresa, id_ubicacion) REFERENCES cau_ubicaciones (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_cau_existencias_empresa FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cau_operaciones (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_empresa INT NOT NULL,
  tipo ENUM('articulo_guardar','articulo_archivar','entrada','ajuste','traslado','entrega','devolucion','cambio_uniforme','reversion','acuse','mantenimiento_abrir','mantenimiento_cerrar','paquete_guardar','tallas_guardar','solicitud_crear','solicitud_resolver') NOT NULL,
  idempotency_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  request_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'SHA-256 del payload canonico y contexto de la operacion',
  estado ENUM('procesando','completada','fallida') NOT NULL DEFAULT 'procesando',
  resultado_json JSON NULL,
  http_status SMALLINT UNSIGNED NULL,
  completed_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by INT NOT NULL,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  updated_by INT NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cau_operaciones_empresa_id (id_empresa, id),
  CONSTRAINT ck_cau_operaciones_version CHECK (version > 0),
  UNIQUE KEY uq_cau_ope_idempotencia (id_empresa, idempotency_key),
  KEY ix_cau_ope_estado (id_empresa, estado, created_at),
  CONSTRAINT ck_cau_ope_http CHECK (http_status IS NULL OR http_status BETWEEN 100 AND 599),
  CONSTRAINT ck_cau_ope_cierre CHECK (estado = 'procesando' OR completed_at IS NOT NULL),
  CONSTRAINT fk_cau_operaciones_empresa FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cau_entregas (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_empresa INT NOT NULL,
  folio VARCHAR(60) NOT NULL,
  id_empleado INT NOT NULL,
  id_operacion BIGINT UNSIGNED NOT NULL,
  modalidad ENUM('asignacion','prestamo') NOT NULL,
  fecha_entrega DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  fecha_devolucion_prevista DATE NULL,
  observaciones TEXT NULL,
  estado ENUM('confirmada','cancelada') NOT NULL DEFAULT 'confirmada',
  snapshot_empresa JSON NOT NULL,
  snapshot_empleado JSON NOT NULL,
  motivo_cancelacion TEXT NULL,
  cancelled_at DATETIME(6) NULL,
  cancelled_by INT NULL,
  id_operacion_cancelacion BIGINT UNSIGNED NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by INT NOT NULL,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  updated_by INT NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cau_entregas_empresa_id (id_empresa, id),
  CONSTRAINT ck_cau_entregas_version CHECK (version > 0),
  UNIQUE KEY uq_cau_ent_folio (id_empresa, folio),
  UNIQUE KEY uq_cau_ent_operacion (id_empresa, id_operacion),
  KEY ix_cau_ent_empleado (id_empresa, id_empleado, estado, fecha_entrega),
  KEY ix_cau_ent_vencimiento (id_empresa, estado, fecha_devolucion_prevista),
  CONSTRAINT ck_cau_ent_cancelacion CHECK ((estado = 'confirmada' AND cancelled_at IS NULL AND cancelled_by IS NULL AND motivo_cancelacion IS NULL AND id_operacion_cancelacion IS NULL) OR (estado = 'cancelada' AND cancelled_at IS NOT NULL AND cancelled_by IS NOT NULL AND id_operacion_cancelacion IS NOT NULL AND motivo_cancelacion IS NOT NULL AND CHAR_LENGTH(TRIM(motivo_cancelacion)) > 0)),
  CONSTRAINT fk_entregas_operacion FOREIGN KEY (id_empresa, id_operacion) REFERENCES cau_operaciones (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_entregas_reversion FOREIGN KEY (id_empresa, id_operacion_cancelacion) REFERENCES cau_operaciones (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_cau_entregas_empresa FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cau_entrega_detalle (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_empresa INT NOT NULL,
  id_entrega BIGINT UNSIGNED NOT NULL,
  id_articulo BIGINT UNSIGNED NOT NULL,
  id_ubicacion_origen BIGINT UNSIGNED NOT NULL,
  cantidad INT UNSIGNED NOT NULL,
  snapshot_articulo JSON NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by INT NOT NULL,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  updated_by INT NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cau_entrega_detalle_empresa_id (id_empresa, id),
  CONSTRAINT ck_cau_entrega_detalle_version CHECK (version > 0),
  UNIQUE KEY uq_cau_end_articulo (id_empresa, id_entrega, id_articulo),
  KEY ix_cau_end_articulo (id_empresa, id_articulo),
  CONSTRAINT ck_cau_end_cantidad CHECK (cantidad > 0),
  CONSTRAINT fk_entrega_detalle_entrega FOREIGN KEY (id_empresa, id_entrega) REFERENCES cau_entregas (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_entrega_detalle_articulo FOREIGN KEY (id_empresa, id_articulo) REFERENCES cau_articulos (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_entrega_detalle_ubicacion FOREIGN KEY (id_empresa, id_ubicacion_origen) REFERENCES cau_ubicaciones (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_cau_entrega_detalle_empresa FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cau_devoluciones (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_empresa INT NOT NULL,
  folio VARCHAR(60) NOT NULL,
  id_empleado INT NOT NULL,
  id_operacion BIGINT UNSIGNED NOT NULL,
  fecha DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  observaciones TEXT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by INT NOT NULL,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  updated_by INT NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cau_devoluciones_empresa_id (id_empresa, id),
  CONSTRAINT ck_cau_devoluciones_version CHECK (version > 0),
  UNIQUE KEY uq_cau_dev_folio (id_empresa, folio),
  UNIQUE KEY uq_cau_dev_operacion (id_empresa, id_operacion),
  KEY ix_cau_dev_empleado (id_empresa, id_empleado, fecha),
  CONSTRAINT fk_devoluciones_operacion FOREIGN KEY (id_empresa, id_operacion) REFERENCES cau_operaciones (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_cau_devoluciones_empresa FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cau_devolucion_detalle (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_empresa INT NOT NULL,
  id_devolucion BIGINT UNSIGNED NOT NULL,
  id_entrega_detalle BIGINT UNSIGNED NOT NULL,
  id_ubicacion_destino BIGINT UNSIGNED NULL,
  cantidad INT UNSIGNED NOT NULL,
  condicion ENUM('bueno','revision','perdido') NOT NULL,
  motivo TEXT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by INT NOT NULL,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  updated_by INT NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cau_devolucion_detalle_empresa_id (id_empresa, id),
  CONSTRAINT ck_cau_devolucion_detalle_version CHECK (version > 0),
  UNIQUE KEY uq_cau_ded_partida_cond (id_empresa, id_devolucion, id_entrega_detalle, condicion),
  KEY ix_cau_ded_entrega (id_empresa, id_entrega_detalle),
  CONSTRAINT ck_cau_ded_cantidad CHECK (cantidad > 0),
  CONSTRAINT ck_cau_ded_motivo CHECK (condicion = 'bueno' OR (motivo IS NOT NULL AND CHAR_LENGTH(TRIM(motivo)) > 0)),
  CONSTRAINT ck_cau_ded_destino CHECK ((condicion = 'perdido' AND id_ubicacion_destino IS NULL) OR (condicion IN ('bueno','revision') AND id_ubicacion_destino IS NOT NULL)),
  CONSTRAINT fk_devolucion_detalle_devolucion FOREIGN KEY (id_empresa, id_devolucion) REFERENCES cau_devoluciones (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_devolucion_detalle_partida FOREIGN KEY (id_empresa, id_entrega_detalle) REFERENCES cau_entrega_detalle (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_devolucion_detalle_ubicacion FOREIGN KEY (id_empresa, id_ubicacion_destino) REFERENCES cau_ubicaciones (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_cau_devolucion_detalle_empresa FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cau_acuses (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_empresa INT NOT NULL,
  id_entrega BIGINT UNSIGNED NOT NULL,
  id_operacion BIGINT UNSIGNED NOT NULL,
  id_empleado INT NOT NULL,
  id_usuario_confirma INT NOT NULL,
  resultado ENUM('recibido','con_diferencia') NOT NULL,
  observaciones TEXT NULL,
  fecha_confirmacion DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  evidencia_storage_key VARCHAR(500) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by INT NOT NULL,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  updated_by INT NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cau_acuses_empresa_id (id_empresa, id),
  CONSTRAINT ck_cau_acuses_version CHECK (version > 0),
  UNIQUE KEY uq_cau_acu_entrega (id_empresa, id_entrega),
  UNIQUE KEY uq_cau_acu_operacion (id_empresa, id_operacion),
  KEY ix_cau_acu_empleado (id_empresa, id_empleado),
  CONSTRAINT ck_cau_acu_observaciones CHECK (resultado = 'recibido' OR (observaciones IS NOT NULL AND CHAR_LENGTH(TRIM(observaciones)) > 0)),
  CONSTRAINT fk_acuses_entrega FOREIGN KEY (id_empresa, id_entrega) REFERENCES cau_entregas (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_acuses_operacion FOREIGN KEY (id_empresa, id_operacion) REFERENCES cau_operaciones (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_cau_acuses_empresa FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cau_mantenimientos (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_empresa INT NOT NULL,
  id_articulo BIGINT UNSIGNED NOT NULL,
  id_ubicacion BIGINT UNSIGNED NOT NULL,
  id_devolucion_detalle BIGINT UNSIGNED NULL,
  id_operacion_apertura BIGINT UNSIGNED NOT NULL,
  id_operacion_cierre BIGINT UNSIGNED NULL,
  cantidad INT UNSIGNED NOT NULL,
  motivo TEXT NOT NULL,
  proveedor VARCHAR(180) NULL,
  id_usuario_responsable INT NULL,
  fecha_ingreso DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  fecha_estimada DATE NULL,
  fecha_cierre DATETIME(6) NULL,
  estado ENUM('abierto','reparado','baja') NOT NULL DEFAULT 'abierto',
  costo DECIMAL(12,2) NOT NULL DEFAULT 0,
  resolucion TEXT NULL,
  closed_by INT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by INT NOT NULL,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  updated_by INT NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cau_mantenimientos_empresa_id (id_empresa, id),
  CONSTRAINT ck_cau_mantenimientos_version CHECK (version > 0),
  UNIQUE KEY uq_cau_man_devolucion (id_empresa, id_devolucion_detalle),
  KEY ix_cau_man_estado (id_empresa, estado, fecha_estimada),
  CONSTRAINT ck_cau_man_cantidad CHECK (cantidad > 0),
  CONSTRAINT ck_cau_man_costo CHECK (costo >= 0),
  CONSTRAINT ck_cau_man_motivo CHECK (CHAR_LENGTH(TRIM(motivo)) > 0),
  CONSTRAINT ck_cau_man_cierre CHECK ((estado = 'abierto' AND fecha_cierre IS NULL AND closed_by IS NULL AND id_operacion_cierre IS NULL) OR (estado IN ('reparado','baja') AND fecha_cierre IS NOT NULL AND closed_by IS NOT NULL AND id_operacion_cierre IS NOT NULL AND resolucion IS NOT NULL AND CHAR_LENGTH(TRIM(resolucion)) > 0)),
  CONSTRAINT ck_cau_man_fechas CHECK (fecha_cierre IS NULL OR fecha_cierre >= fecha_ingreso),
  CONSTRAINT fk_mantenimientos_articulo FOREIGN KEY (id_empresa, id_articulo) REFERENCES cau_articulos (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_mantenimientos_ubicacion FOREIGN KEY (id_empresa, id_ubicacion) REFERENCES cau_ubicaciones (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_mantenimientos_devolucion FOREIGN KEY (id_empresa, id_devolucion_detalle) REFERENCES cau_devolucion_detalle (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_mantenimientos_apertura FOREIGN KEY (id_empresa, id_operacion_apertura) REFERENCES cau_operaciones (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_mantenimientos_cierre FOREIGN KEY (id_empresa, id_operacion_cierre) REFERENCES cau_operaciones (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_cau_mantenimientos_empresa FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cau_movimientos (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_empresa INT NOT NULL,
  id_operacion BIGINT UNSIGNED NOT NULL,
  secuencia SMALLINT UNSIGNED NOT NULL,
  id_articulo BIGINT UNSIGNED NOT NULL,
  id_empleado INT NULL,
  id_entrega_detalle BIGINT UNSIGNED NULL,
  id_devolucion_detalle BIGINT UNSIGNED NULL,
  id_mantenimiento BIGINT UNSIGNED NULL,
  id_movimiento_revertido BIGINT UNSIGNED NULL,
  id_ubicacion_origen BIGINT UNSIGNED NULL,
  id_ubicacion_destino BIGINT UNSIGNED NULL,
  estado_origen ENUM('externo','disponible','asignado','revision','baja') NOT NULL,
  estado_destino ENUM('externo','disponible','asignado','revision','baja') NOT NULL,
  tipo ENUM('entrada','entrega','devolucion','traslado','ajuste','perdida','mantenimiento_ingreso','mantenimiento_salida','reversion') NOT NULL,
  cantidad INT UNSIGNED NOT NULL,
  fecha DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  motivo TEXT NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by INT NOT NULL,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  updated_by INT NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cau_movimientos_empresa_id (id_empresa, id),
  CONSTRAINT ck_cau_movimientos_version CHECK (version > 0),
  UNIQUE KEY uq_cau_mov_secuencia (id_empresa, id_operacion, secuencia),
  KEY ix_cau_mov_fecha (id_empresa, fecha, id),
  KEY ix_cau_mov_articulo (id_empresa, id_articulo, fecha),
  KEY ix_cau_mov_empleado (id_empresa, id_empleado, fecha),
  CONSTRAINT ck_cau_mov_cantidad CHECK (cantidad > 0 AND secuencia > 0),
  CONSTRAINT ck_cau_mov_motivo CHECK (CHAR_LENGTH(TRIM(motivo)) > 0),
  CONSTRAINT ck_cau_mov_origen CHECK (estado_origen NOT IN ('disponible','revision','baja') OR id_ubicacion_origen IS NOT NULL),
  CONSTRAINT ck_cau_mov_destino CHECK (estado_destino NOT IN ('disponible','revision','baja') OR id_ubicacion_destino IS NOT NULL),
  CONSTRAINT ck_cau_mov_empleado CHECK ((estado_origen <> 'asignado' AND estado_destino <> 'asignado') OR id_empleado IS NOT NULL),
  CONSTRAINT fk_movimientos_operacion FOREIGN KEY (id_empresa, id_operacion) REFERENCES cau_operaciones (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_movimientos_articulo FOREIGN KEY (id_empresa, id_articulo) REFERENCES cau_articulos (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_movimientos_entrega FOREIGN KEY (id_empresa, id_entrega_detalle) REFERENCES cau_entrega_detalle (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_movimientos_devolucion FOREIGN KEY (id_empresa, id_devolucion_detalle) REFERENCES cau_devolucion_detalle (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_movimientos_mantenimiento FOREIGN KEY (id_empresa, id_mantenimiento) REFERENCES cau_mantenimientos (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_movimientos_revertido FOREIGN KEY (id_empresa, id_movimiento_revertido) REFERENCES cau_movimientos (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_movimientos_origen FOREIGN KEY (id_empresa, id_ubicacion_origen) REFERENCES cau_ubicaciones (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_movimientos_destino FOREIGN KEY (id_empresa, id_ubicacion_destino) REFERENCES cau_ubicaciones (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_cau_movimientos_empresa FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cau_paquetes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_empresa INT NOT NULL,
  nombre VARCHAR(160) NOT NULL,
  id_puesto INT NULL,
  descripcion TEXT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by INT NOT NULL,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  updated_by INT NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cau_paquetes_empresa_id (id_empresa, id),
  CONSTRAINT ck_cau_paquetes_version CHECK (version > 0),
  UNIQUE KEY uq_cau_paq_nombre (id_empresa, nombre),
  KEY ix_cau_paq_puesto (id_empresa, id_puesto, activo),
  CONSTRAINT ck_cau_paq_activo CHECK (activo IN (0,1)),
  CONSTRAINT fk_cau_paquetes_empresa FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cau_paquete_detalle (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_empresa INT NOT NULL,
  id_paquete BIGINT UNSIGNED NOT NULL,
  id_articulo BIGINT UNSIGNED NOT NULL,
  cantidad INT UNSIGNED NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by INT NOT NULL,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  updated_by INT NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cau_paquete_detalle_empresa_id (id_empresa, id),
  CONSTRAINT ck_cau_paquete_detalle_version CHECK (version > 0),
  UNIQUE KEY uq_cau_pad_articulo (id_empresa, id_paquete, id_articulo),
  CONSTRAINT ck_cau_pad_cantidad CHECK (cantidad > 0),
  CONSTRAINT fk_paquete_detalle_paquete FOREIGN KEY (id_empresa, id_paquete) REFERENCES cau_paquetes (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_paquete_detalle_articulo FOREIGN KEY (id_empresa, id_articulo) REFERENCES cau_articulos (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_cau_paquete_detalle_empresa FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cau_empleado_tallas (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_empresa INT NOT NULL,
  id_empleado INT NOT NULL,
  talla_superior VARCHAR(30) NULL,
  talla_pantalon VARCHAR(30) NULL,
  talla_calzado VARCHAR(30) NULL,
  sistema_calzado VARCHAR(20) NULL COMMENT 'Ejemplos: MX, US, EU o CM',
  observaciones TEXT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by INT NOT NULL,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  updated_by INT NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cau_empleado_tallas_empresa_id (id_empresa, id),
  CONSTRAINT ck_cau_empleado_tallas_version CHECK (version > 0),
  UNIQUE KEY uq_cau_tal_empleado (id_empresa, id_empleado),
  CONSTRAINT fk_cau_empleado_tallas_empresa FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE cau_solicitudes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  id_empresa INT NOT NULL,
  id_empleado INT NOT NULL,
  id_entrega_detalle BIGINT UNSIGNED NULL,
  tipo ENUM('falla_equipo','cambio_talla','reposicion','otro') NOT NULL,
  descripcion TEXT NOT NULL,
  estado ENUM('pendiente','en_proceso','resuelta','rechazada') NOT NULL DEFAULT 'pendiente',
  id_usuario_responsable INT NULL,
  respuesta TEXT NULL,
  fecha_resolucion DATETIME(6) NULL,
  resolved_by INT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by INT NOT NULL,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  updated_by INT NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cau_solicitudes_empresa_id (id_empresa, id),
  CONSTRAINT ck_cau_solicitudes_version CHECK (version > 0),
  KEY ix_cau_sol_estado (id_empresa, estado, created_at),
  KEY ix_cau_sol_empleado (id_empresa, id_empleado, created_at),
  CONSTRAINT ck_cau_sol_descripcion CHECK (CHAR_LENGTH(TRIM(descripcion)) > 0),
  CONSTRAINT ck_cau_sol_cierre CHECK ((estado IN ('pendiente','en_proceso') AND fecha_resolucion IS NULL AND resolved_by IS NULL) OR (estado IN ('resuelta','rechazada') AND fecha_resolucion IS NOT NULL AND resolved_by IS NOT NULL AND respuesta IS NOT NULL AND CHAR_LENGTH(TRIM(respuesta)) > 0)),
  CONSTRAINT fk_solicitudes_entrega FOREIGN KEY (id_empresa, id_entrega_detalle) REFERENCES cau_entrega_detalle (id_empresa, id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT fk_cau_solicitudes_empresa FOREIGN KEY (id_empresa) REFERENCES empresas (id_empresa) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SELECT TABLE_SCHEMA, COUNT(*) AS tablas_cau
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME LIKE 'cau\_%'
GROUP BY TABLE_SCHEMA;

SELECT TABLE_NAME FROM information_schema.TABLES
WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME LIKE 'cau\_%'
ORDER BY TABLE_NAME;